### ISSUE TITLE
Share files in Autodesk A360 cloud service

### ISSUE THREAD

**Issue by Scott216** [shapeoko/Shapeoko_2#6]
Can you upload the Inventor CAD files to Autodesk's A360 cloud service and them make them public:

See: http://forums.autodesk.com/t5/post-your-tips-and-tutorials/walking-on-clouds-moving-data-from-inventor-into-fusion-360-via/td-p/5496907

**Comment by shapeoko** [comment]
I'll see what I can do to make sure it's updated and then post it public.
